name: News Feed API

on: [push]

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./infra/cdk

      - name: Run tests
        run: npm test
        working-directory: ./infra/cdk

  deploy-infra:
    runs-on: ubuntu-latest
    needs: test-infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./infra/cdk

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS
        run: cdk deploy --all --require-approval=never
        working-directory: ./infra/cdk

  lint-search-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files
        working-directory: ./services/search-service

  test-search-service:
    runs-on: ubuntu-latest
    needs: lint-search-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run tests
        run: poetry run pytest
        working-directory: ./services/search-service
