name: Search Service

on:
  push:
    branches:
      - main
    paths:
      - 'services/search-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/search-service/**'

jobs:
  lint-search-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files
        working-directory: ./services/search-service

  test-search-service:
    runs-on: ubuntu-latest
    needs: lint-search-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run tests
        run: poetry run pytest
        working-directory: ./services/search-service
