name: Search Service

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-account-id:
        required: true

jobs:
  lint-search-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files
        working-directory: ./services/search-service

  test-search-service:
    runs-on: ubuntu-latest
    needs: lint-search-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Run tests
        run: poetry run pytest
        working-directory: ./services/search-service

  push-search-service-image-to-ecr:
    runs-on: ubuntu-latest
    needs: test-search-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        run: pip install poetry
        working-directory: ./services/search-service

      - name: Install dependencies
        run: poetry install
        working-directory: ./services/search-service

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t ${{ secrets.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/search-service:$GITHUB_SHA .
        working-directory: ./services/search-service

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/search-service:$GITHUB_SHA

      - name: Refresh EC2 instances
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name NewsFeedApiSearchServiceAutoScalingGroup --region us-east-1
